feat-ios-sdk
trackier/unity-sdk pull request #14
Opened 2022-10-27 12:34 UTC by IloveJavaa

feat-ios-sdk
Link - https://app.asana.com/0/0/1203232843311351/f

2022-10-28 10:39 UTC, Hemant-Mann requested changes

2022-10-28 10:39 UTC, Hemant-Mann commented on Assets/Trackier/iOS/TrackieriOS.cs
> +#if UNITY_IOS
this if can be removed because there is an if above @IloveJavaa

2022-10-28 16:42 UTC, IloveJavaa commented on Assets/Trackier/iOS/TrackieriOS.cs
> +#if UNITY_IOS
Done

2022-11-16 09:27 UTC, Hemant-Mann commented on Assets/Trackier/Android/TrackierAndroid.cs
> +		catch(System.Exception e){
```suggestion
		catch(System.Exception e) {
```

2022-11-16 09:27 UTC, Hemant-Mann commented on Assets/Trackier/Android/TrackierAndroid.cs
> +		catch(System.Exception e){
```suggestion
		catch(System.Exception e) {
```

2022-11-17 05:13 UTC, IloveJavaa commented on Assets/Trackier/Android/TrackierAndroid.cs
> +		catch(System.Exception e){
Done

2022-11-17 05:13 UTC, IloveJavaa commented on Assets/Trackier/Android/TrackierAndroid.cs
> +		catch(System.Exception e){
Done

2022-11-18 12:07 UTC, Hemant-Mann approved these changes

2022-11-18 12:07 UTC, merged